// Nyth Router provider registry - May 2026 snapshot.
// Each entry is metadata only by default. Some providers are flagged as
// "implemented" because they share OpenAI- or Anthropic-compatible APIs that
// Nyth Router's adapters can route to without provider-specific SDKs.
//
// Capabilities use these tags:
//   chat, completion, embeddings, image, vision, audio, rerank, tools, streaming
//
// Format values:
//   openai-compatible | anthropic-compatible | native | local
//
// Status values:
//   implemented      - works through Nyth Router adapters today
//   metadata-only    - listed in registry, no live adapter yet
//   planned          - adapter on the roadmap
//
// All pricing values are USD per 1K tokens. `null` means unknown.

const registry = [
  // 1) OpenAI-compatible cloud providers
  {
    id: 'openai',
    name: 'OpenAI',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.openai.com/v1',
    authType: 'bearer',
    capabilities: ['chat', 'completion', 'embeddings', 'image', 'vision', 'audio', 'tools', 'streaming'],
    docsUrl: 'https://platform.openai.com/docs',
    status: 'implemented',
    models: [
      { id: 'gpt-5.5', display: 'GPT-5.5', context: 1000000, in: 4, out: 12, capabilities: ['chat', 'tools', 'vision', 'streaming'], status: 'GA', tags: ['frontier', 'reasoning'] },
      { id: 'gpt-5.5-mini', display: 'GPT-5.5 Mini', context: 400000, in: 0.5, out: 1.5, capabilities: ['chat', 'tools', 'vision', 'streaming'], status: 'GA', tags: ['fast', 'cheap'] },
      { id: 'gpt-5', display: 'GPT-5', context: 600000, in: 2, out: 8, capabilities: ['chat', 'tools', 'vision', 'streaming'], status: 'GA', tags: ['frontier'] },
      { id: 'gpt-5-mini', display: 'GPT-5 Mini', context: 200000, in: 0.3, out: 1.2, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['cheap'] },
      { id: 'gpt-5-codex', display: 'GPT-5 Codex', context: 400000, in: 1.25, out: 10, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['code', 'agentic-coding', 'codex'] },
      { id: 'codex-1', display: 'Codex 1', context: 200000, in: 1.5, out: 6, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['code', 'codex'] },
      { id: 'gpt-4.1', display: 'GPT-4.1', context: 200000, in: 2, out: 8, capabilities: ['chat', 'tools', 'vision', 'streaming'], status: 'GA', tags: ['stable'] },
      { id: 'gpt-4.1-mini', display: 'GPT-4.1 Mini', context: 128000, in: 0.4, out: 1.6, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['fast'] },
      { id: 'o4', display: 'o4', context: 200000, in: 4, out: 16, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['reasoning'] },
      { id: 'o4-mini', display: 'o4 Mini', context: 128000, in: 1.1, out: 4.4, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['reasoning', 'cheap'] },
      { id: 'text-embedding-3-large', display: 'Embedding 3 Large', context: 8192, in: 0.13, out: 0, capabilities: ['embeddings'], status: 'GA', tags: ['embedding'] },
      { id: 'text-embedding-3-small', display: 'Embedding 3 Small', context: 8192, in: 0.02, out: 0, capabilities: ['embeddings'], status: 'GA', tags: ['embedding'] },
    ],
  },
  {
    id: 'codex',
    name: 'OpenAI Codex OAuth',
    category: 'oauth',
    format: 'codex-account',
    baseUrl: 'https://chatgpt.com/backend-api/codex',
    authType: 'oauth-connected',
    capabilities: ['chat', 'completion', 'embeddings', 'image', 'vision', 'audio', 'tools', 'streaming'],
    docsUrl: 'https://developers.openai.com/codex',
    status: 'implemented',
    notes: 'Uses a connected OpenAI/Codex OAuth account. Exposes the same OpenAI model catalog through account quota instead of a provider API key.',
    models: [
      { id: 'gpt-5.5', display: 'GPT-5.5', context: 1000000, in: null, out: null, capabilities: ['chat', 'tools', 'vision', 'streaming'], status: 'oauth', tags: ['frontier', 'reasoning', 'oauth'] },
      { id: 'gpt-5.5-mini', display: 'GPT-5.5 Mini', context: 400000, in: null, out: null, capabilities: ['chat', 'tools', 'vision', 'streaming'], status: 'oauth', tags: ['fast', 'cheap', 'oauth'] },
      { id: 'gpt-5', display: 'GPT-5', context: 600000, in: null, out: null, capabilities: ['chat', 'tools', 'vision', 'streaming'], status: 'oauth', tags: ['frontier', 'oauth'] },
      { id: 'gpt-5-mini', display: 'GPT-5 Mini', context: 200000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'oauth', tags: ['cheap', 'oauth'] },
      { id: 'gpt-5-codex', display: 'GPT-5 Codex', context: 400000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'oauth', tags: ['code', 'agentic-coding', 'codex', 'oauth'] },
      { id: 'codex-1', display: 'Codex 1', context: 200000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'oauth', tags: ['code', 'codex', 'oauth'] },
      { id: 'gpt-4.1', display: 'GPT-4.1', context: 200000, in: null, out: null, capabilities: ['chat', 'tools', 'vision', 'streaming'], status: 'oauth', tags: ['stable', 'oauth'] },
      { id: 'gpt-4.1-mini', display: 'GPT-4.1 Mini', context: 128000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'oauth', tags: ['fast', 'oauth'] },
      { id: 'o4', display: 'o4', context: 200000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'oauth', tags: ['reasoning', 'oauth'] },
      { id: 'o4-mini', display: 'o4 Mini', context: 128000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'oauth', tags: ['reasoning', 'cheap', 'oauth'] },
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    category: 'cloud',
    format: 'anthropic-compatible',
    baseUrl: 'https://api.anthropic.com',
    authType: 'x-api-key',
    capabilities: ['chat', 'vision', 'tools', 'streaming'],
    docsUrl: 'https://docs.anthropic.com',
    status: 'implemented',
    models: [
      { id: 'claude-opus-4.7', display: 'Claude Opus 4.7', context: 500000, in: 12, out: 60, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'GA', tags: ['frontier', 'reasoning'] },
      { id: 'claude-opus-4.5', display: 'Claude Opus 4.5', context: 400000, in: 10, out: 50, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'GA', tags: ['frontier'] },
      { id: 'claude-sonnet-4.5', display: 'Claude Sonnet 4.5', context: 400000, in: 3, out: 15, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'GA', tags: ['balanced'] },
      { id: 'claude-sonnet-4.2', display: 'Claude Sonnet 4.2', context: 200000, in: 2, out: 10, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'GA', tags: ['balanced'] },
      { id: 'claude-haiku-4', display: 'Claude Haiku 4', context: 200000, in: 0.25, out: 1.25, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['fast', 'cheap'] },
      { id: 'claude-haiku-3.5', display: 'Claude Haiku 3.5', context: 200000, in: 0.2, out: 1.0, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['cheap'] },
    ],
  },

  {
    id: 'claude-oauth',
    name: 'Claude Code OAuth',
    category: 'oauth',
    format: 'anthropic-compatible',
    baseUrl: 'https://api.anthropic.com',
    authType: 'oauth-connected',
    capabilities: ['chat', 'vision', 'tools', 'streaming'],
    docsUrl: 'https://docs.anthropic.com',
    status: 'implemented',
    notes: 'Uses a connected Claude Code OAuth account. Exposes Claude models through account quota instead of an Anthropic API key.',
    models: [
      { id: 'claude-opus-4.7', display: 'Claude Opus 4.7', context: 500000, in: null, out: null, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'oauth', tags: ['frontier', 'reasoning', 'oauth'] },
      { id: 'claude-opus-4.5', display: 'Claude Opus 4.5', context: 400000, in: null, out: null, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'oauth', tags: ['frontier', 'oauth'] },
      { id: 'claude-sonnet-4.5', display: 'Claude Sonnet 4.5', context: 400000, in: null, out: null, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'oauth', tags: ['balanced', 'oauth'] },
      { id: 'claude-sonnet-4.2', display: 'Claude Sonnet 4.2', context: 200000, in: null, out: null, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'oauth', tags: ['balanced', 'oauth'] },
      { id: 'claude-haiku-4', display: 'Claude Haiku 4', context: 200000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'oauth', tags: ['fast', 'cheap', 'oauth'] },
      { id: 'claude-haiku-3.5', display: 'Claude Haiku 3.5', context: 200000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'oauth', tags: ['cheap', 'oauth'] },
    ],
  },
  {
    id: 'google',
    name: 'Google Gemini',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    authType: 'bearer',
    capabilities: ['chat', 'vision', 'audio', 'tools', 'streaming'],
    docsUrl: 'https://ai.google.dev/docs',
    status: 'implemented',
    models: [
      { id: 'gemini-3.5-pro', display: 'Gemini 3.5 Pro', context: 2000000, in: 3.0, out: 12, capabilities: ['chat', 'vision', 'audio', 'tools', 'streaming'], status: 'GA', tags: ['frontier', 'multimodal'] },
      { id: 'gemini-3.5-flash', display: 'Gemini 3.5 Flash', context: 1000000, in: 0.18, out: 0.72, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'GA', tags: ['fast', 'cheap'] },
      { id: 'gemini-3.0-pro', display: 'Gemini 3.0 Pro', context: 2000000, in: 2.5, out: 10, capabilities: ['chat', 'vision', 'audio', 'tools', 'streaming'], status: 'GA', tags: ['stable', 'multimodal'] },
      { id: 'gemini-3.0-flash', display: 'Gemini 3.0 Flash', context: 1000000, in: 0.15, out: 0.6, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'GA', tags: ['fast', 'cheap'] },
      { id: 'gemini-2.5-pro', display: 'Gemini 2.5 Pro', context: 2000000, in: 1.25, out: 5, capabilities: ['chat', 'vision', 'audio', 'tools', 'streaming'], status: 'GA', tags: ['legacy'] },
      { id: 'gemini-2.5-flash', display: 'Gemini 2.5 Flash', context: 1000000, in: 0.1, out: 0.4, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'GA', tags: ['legacy', 'fast'] },
      { id: 'gemini-embedding-3', display: 'Gemini Embedding 3', context: 8192, in: 0.025, out: 0, capabilities: ['embeddings'], status: 'GA', tags: ['embedding'] },
    ],
  },

  {
    id: 'gemini-oauth',
    name: 'Gemini CLI OAuth',
    category: 'oauth',
    format: 'gemini-oauth-account',
    baseUrl: 'https://cloudcode-pa.googleapis.com/v1internal',
    authType: 'oauth-connected',
    capabilities: ['chat', 'vision', 'audio', 'tools', 'streaming'],
    docsUrl: 'https://ai.google.dev/docs',
    status: 'implemented',
    notes: 'Uses a connected Gemini CLI OAuth account. Exposes Gemini models through account quota instead of a Google API key.',
    models: [
      { id: 'gemini-3.5-pro', display: 'Gemini 3.5 Pro', context: 2000000, in: null, out: null, capabilities: ['chat', 'vision', 'audio', 'tools', 'streaming'], status: 'oauth', tags: ['frontier', 'multimodal', 'oauth'] },
      { id: 'gemini-3.5-flash', display: 'Gemini 3.5 Flash', context: 1000000, in: null, out: null, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'oauth', tags: ['fast', 'cheap', 'oauth'] },
      { id: 'gemini-3.0-pro', display: 'Gemini 3.0 Pro', context: 2000000, in: null, out: null, capabilities: ['chat', 'vision', 'audio', 'tools', 'streaming'], status: 'oauth', tags: ['stable', 'multimodal', 'oauth'] },
      { id: 'gemini-3.0-flash', display: 'Gemini 3.0 Flash', context: 1000000, in: null, out: null, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'oauth', tags: ['fast', 'cheap', 'oauth'] },
      { id: 'gemini-2.5-pro', display: 'Gemini 2.5 Pro', context: 2000000, in: null, out: null, capabilities: ['chat', 'vision', 'audio', 'tools', 'streaming'], status: 'oauth', tags: ['legacy', 'oauth'] },
      { id: 'gemini-2.5-flash', display: 'Gemini 2.5 Flash', context: 1000000, in: null, out: null, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'oauth', tags: ['legacy', 'fast', 'oauth'] },
    ],
  },
  {
    id: 'xai',
    name: 'xAI',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.x.ai/v1',
    authType: 'bearer',
    capabilities: ['chat', 'tools', 'streaming'],
    docsUrl: 'https://docs.x.ai',
    status: 'implemented',
    models: [
      { id: 'grok-4', display: 'Grok 4', context: 256000, in: 3, out: 15, capabilities: ['chat', 'tools', 'vision', 'streaming'], status: 'GA', tags: ['frontier'] },
      { id: 'grok-4-0709', display: 'Grok 4 0709', context: 256000, in: 3, out: 15, capabilities: ['chat', 'tools', 'vision', 'streaming'], status: 'GA', tags: ['pinned'] },
      { id: 'grok-4-fast-reasoning', display: 'Grok 4 Fast Reasoning', context: 2000000, in: 0.2, out: 0.5, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['fast', 'reasoning'] },
      { id: 'grok-4-fast-non-reasoning', display: 'Grok 4 Fast Non Reasoning', context: 2000000, in: 0.2, out: 0.5, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['fast'] },
      { id: 'grok-3-latest', display: 'Grok 3 Latest', context: 128000, in: 3, out: 15, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['stable'] },
      { id: 'grok-3-mini-latest', display: 'Grok 3 Mini Latest', context: 128000, in: 0.3, out: 0.5, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['cheap'] },
      { id: 'grok-2-vision-latest', display: 'Grok 2 Vision Latest', context: 32000, in: 2, out: 10, capabilities: ['chat', 'vision', 'streaming'], status: 'GA', tags: ['vision'] },
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.mistral.ai/v1',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'tools', 'streaming'],
    docsUrl: 'https://docs.mistral.ai',
    status: 'implemented',
    models: [
      { id: 'mistral-large-latest', display: 'Mistral Large Latest', context: 128000, in: 2, out: 6, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['frontier'] },
      { id: 'mistral-medium-latest', display: 'Mistral Medium Latest', context: 128000, in: 0.5, out: 2, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['balanced'] },
      { id: 'mistral-small-latest', display: 'Mistral Small Latest', context: 32000, in: 0.1, out: 0.3, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['cheap'] },
      { id: 'magistral-medium-latest', display: 'Magistral Medium Latest', context: 128000, in: 2, out: 5, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['reasoning'] },
      { id: 'codestral-latest', display: 'Codestral Latest', context: 256000, in: 0.3, out: 0.9, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['code'] },
      { id: 'devstral-small-latest', display: 'Devstral Small Latest', context: 128000, in: 0.1, out: 0.3, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['code', 'agent'] },
      { id: 'pixtral-large-latest', display: 'Pixtral Large Latest', context: 128000, in: 2, out: 6, capabilities: ['chat', 'vision', 'streaming'], status: 'GA', tags: ['vision'] },
      { id: 'mistral-embed', display: 'Mistral Embed', context: 8192, in: 0.1, out: 0, capabilities: ['embeddings'], status: 'GA', tags: ['embedding'] },
    ],
  },
  {
    id: 'cohere',
    name: 'Cohere',
    category: 'cloud',
    format: 'native',
    baseUrl: 'https://api.cohere.ai/v2',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'rerank', 'tools', 'streaming'],
    docsUrl: 'https://docs.cohere.com',
    status: 'metadata-only',
    models: [
      { id: 'command-a-03-2026', display: 'Command A (2026-03)', context: 256000, in: 1.5, out: 6, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['enterprise'] },
      { id: 'command-r-plus-08-2025', display: 'Command R+ (2025-08)', context: 128000, in: 1.5, out: 6, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['rag'] },
      { id: 'embed-v4', display: 'Embed v4', context: 8192, in: 0.1, out: 0, capabilities: ['embeddings'], status: 'GA', tags: ['embedding'] },
      { id: 'rerank-v4', display: 'Rerank v4', context: 4096, in: 0.5, out: 0, capabilities: ['rerank'], status: 'GA', tags: ['rerank'] },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.deepseek.com/v1',
    authType: 'bearer',
    capabilities: ['chat', 'tools', 'streaming'],
    docsUrl: 'https://platform.deepseek.com/docs',
    status: 'implemented',
    models: [
      { id: 'deepseek-chat', display: 'DeepSeek Chat', context: 64000, in: 0.27, out: 1.1, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['official', 'cheap'] },
      { id: 'deepseek-reasoner', display: 'DeepSeek Reasoner', context: 64000, in: 0.55, out: 2.2, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['official', 'reasoning'] },
      { id: 'deepseek-coder', display: 'DeepSeek Coder', context: 64000, in: 0.27, out: 1.1, capabilities: ['chat', 'tools', 'streaming'], status: 'legacy', tags: ['code'] },
    ],
  },
  {
    id: 'groq',
    name: 'Groq',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.groq.com/openai/v1',
    authType: 'bearer',
    capabilities: ['chat', 'tools', 'streaming', 'audio'],
    docsUrl: 'https://console.groq.com/docs',
    status: 'implemented',
    models: [
      { id: 'llama-3.3-70b-versatile', display: 'Llama 3.3 70B Versatile', context: 128000, in: 0.59, out: 0.79, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['fast', 'open'] },
      { id: 'llama-3.1-8b-instant', display: 'Llama 3.1 8B Instant', context: 128000, in: 0.05, out: 0.08, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['fast', 'cheap'] },
      { id: 'meta-llama/llama-4-scout-17b-16e-instruct', display: 'Llama 4 Scout 17B 16E', context: 128000, in: 0.11, out: 0.34, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['fast', 'open'] },
      { id: 'meta-llama/llama-4-maverick-17b-128e-instruct', display: 'Llama 4 Maverick 17B 128E', context: 128000, in: 0.2, out: 0.6, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['open'] },
      { id: 'deepseek-r1-distill-llama-70b', display: 'DeepSeek R1 Distill Llama 70B', context: 128000, in: 0.75, out: 0.99, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['reasoning'] },
      { id: 'qwen/qwen3-32b', display: 'Qwen3 32B', context: 128000, in: 0.29, out: 0.59, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['fast'] },
      { id: 'moonshotai/kimi-k2-instruct', display: 'Kimi K2 Instruct', context: 128000, in: 1.0, out: 3.0, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['agent'] },
      { id: 'openai/gpt-oss-120b', display: 'GPT OSS 120B', context: 128000, in: 0.15, out: 0.75, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['open'] },
      { id: 'whisper-large-v3-turbo', display: 'Whisper Large v3 Turbo', context: 0, in: null, out: null, capabilities: ['audio'], status: 'GA', tags: ['speech'] },
    ],
  },
  {
    id: 'together',
    name: 'Together AI',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.together.xyz/v1',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'image', 'tools', 'streaming'],
    docsUrl: 'https://docs.together.ai',
    status: 'implemented',
    models: [
      { id: 'meta-llama/Llama-4-405B-Instruct', display: 'Llama 4 405B Instruct', context: 128000, in: 1.5, out: 1.5, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['open'] },
      { id: 'Qwen/Qwen3-72B-Instruct', display: 'Qwen3 72B Instruct', context: 128000, in: 0.5, out: 0.5, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['open'] },
      { id: 'deepseek-ai/DeepSeek-V4', display: 'DeepSeek V4 (hosted)', context: 128000, in: 0.7, out: 2.0, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['open'] },
      { id: 'mistralai/Mixtral-8x22B-Instruct-v0.2', display: 'Mixtral 8x22B v0.2', context: 64000, in: 1.2, out: 1.2, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['moe'] },
    ],
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'image', 'tools', 'streaming'],
    docsUrl: 'https://docs.fireworks.ai',
    status: 'implemented',
    models: [
      { id: 'accounts/fireworks/models/llama-v4-405b-instruct', display: 'Llama v4 405B Instruct', context: 128000, in: 1.4, out: 1.4, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['open'] },
      { id: 'accounts/fireworks/models/llama-v4-70b-instruct', display: 'Llama v4 70B Instruct', context: 128000, in: 0.45, out: 0.45, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['fast'] },
      { id: 'accounts/fireworks/models/qwen3-coder-32b', display: 'Qwen3 Coder 32B', context: 128000, in: 0.3, out: 0.3, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['code'] },
    ],
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.perplexity.ai',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://docs.perplexity.ai',
    status: 'implemented',
    models: [
      { id: 'sonar-pro', display: 'Sonar Pro', context: 200000, in: 3, out: 15, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['search'] },
      { id: 'sonar-reasoning', display: 'Sonar Reasoning', context: 128000, in: 5, out: 25, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['search', 'reasoning'] },
      { id: 'sonar-small', display: 'Sonar Small', context: 128000, in: 0.2, out: 0.6, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['search', 'cheap'] },
    ],
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    category: 'aggregator',
    format: 'openai-compatible',
    baseUrl: 'https://openrouter.ai/api/v1',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'vision', 'tools', 'streaming'],
    docsUrl: 'https://openrouter.ai/docs',
    status: 'implemented',
    models: [
      { id: 'openrouter/auto', display: 'OpenRouter Auto', context: 200000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['router'] },
      { id: 'anthropic/claude-opus-4.7', display: 'Claude Opus 4.7 via OR', context: 500000, in: 12, out: 60, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'GA', tags: ['frontier'] },
      { id: 'openai/gpt-5.5', display: 'GPT-5.5 via OR', context: 1000000, in: 4, out: 12, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'GA', tags: ['frontier'] },
      { id: 'openai/gpt-5-codex', display: 'GPT-5 Codex via OR', context: 400000, in: 1.25, out: 10, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['code', 'codex'] },
      { id: 'google/gemini-3.0-pro', display: 'Gemini 3.0 Pro via OR', context: 2000000, in: 2.5, out: 10, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'GA', tags: ['multimodal'] },
    ],
  },
  {
    id: 'azure-openai',
    name: 'Azure OpenAI',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://YOUR-RESOURCE.openai.azure.com/openai',
    authType: 'api-key',
    capabilities: ['chat', 'embeddings', 'vision', 'audio', 'tools', 'streaming'],
    docsUrl: 'https://learn.microsoft.com/azure/ai-services/openai/',
    status: 'metadata-only',
    notes: 'Requires Azure resource, deployment name, and API version.',
    models: [
      { id: 'gpt-5.5', display: 'GPT-5.5 (Azure deployment)', context: 1000000, in: 4, out: 12, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'GA', tags: ['frontier'] },
      { id: 'gpt-5-mini', display: 'GPT-5 Mini (Azure deployment)', context: 200000, in: 0.3, out: 1.2, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['cheap'] },
    ],
  },
  {
    id: 'aws-bedrock',
    name: 'AWS Bedrock',
    category: 'cloud',
    format: 'native',
    baseUrl: 'https://bedrock-runtime.us-east-1.amazonaws.com',
    authType: 'sigv4',
    capabilities: ['chat', 'embeddings', 'image', 'vision', 'tools', 'streaming'],
    docsUrl: 'https://docs.aws.amazon.com/bedrock/',
    status: 'metadata-only',
    notes: 'Requires SigV4 signing. Use the AWS SDK adapter when implemented.',
    models: [
      { id: 'anthropic.claude-opus-4-5', display: 'Claude Opus 4.5 (Bedrock)', context: 400000, in: 10, out: 50, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'GA', tags: ['frontier'] },
      { id: 'meta.llama4-405b-instruct', display: 'Llama 4 405B (Bedrock)', context: 128000, in: 1.5, out: 1.5, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['open'] },
      { id: 'amazon.titan-text-premier-v1', display: 'Titan Text Premier', context: 32000, in: 0.5, out: 1.5, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['amazon'] },
    ],
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare Workers AI',
    category: 'serverless',
    format: 'openai-compatible',
    baseUrl: 'https://api.cloudflare.com/client/v4/accounts/ACCOUNT_ID/ai',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'image', 'audio', 'streaming'],
    docsUrl: 'https://developers.cloudflare.com/workers-ai',
    status: 'metadata-only',
    models: [
      { id: '@cf/meta/llama-4-70b-instruct', display: 'Llama 4 70B Instruct', context: 32000, in: 0.4, out: 0.4, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['edge'] },
      { id: '@cf/openai/whisper-v4', display: 'Whisper v4', context: 0, in: null, out: null, capabilities: ['audio'], status: 'GA', tags: ['speech'] },
    ],
  },
  {
    id: 'replicate',
    name: 'Replicate',
    category: 'serverless',
    format: 'native',
    baseUrl: 'https://api.replicate.com/v1',
    authType: 'bearer',
    capabilities: ['chat', 'image', 'audio', 'streaming'],
    docsUrl: 'https://replicate.com/docs',
    status: 'metadata-only',
    models: [
      { id: 'meta/meta-llama-4-405b-instruct', display: 'Llama 4 405B Instruct', context: 128000, in: 2.5, out: 2.5, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['open'] },
      { id: 'black-forest-labs/flux-2-pro', display: 'FLUX 2 Pro', context: 0, in: null, out: null, capabilities: ['image'], status: 'GA', tags: ['image'] },
    ],
  },
  {
    id: 'huggingface',
    name: 'Hugging Face Inference',
    category: 'serverless',
    format: 'openai-compatible',
    baseUrl: 'https://api-inference.huggingface.co/v1',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'image', 'audio', 'streaming'],
    docsUrl: 'https://huggingface.co/docs/inference-providers',
    status: 'implemented',
    models: [
      { id: 'meta-llama/Llama-4-70B-Instruct', display: 'Llama 4 70B Instruct', context: 128000, in: 0.5, out: 0.5, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['open'] },
      { id: 'Qwen/Qwen3-Coder-32B', display: 'Qwen3 Coder 32B', context: 128000, in: 0.3, out: 0.3, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['code'] },
    ],
  },
  {
    id: 'modal',
    name: 'Modal',
    category: 'serverless',
    format: 'openai-compatible',
    baseUrl: 'https://YOUR-DEPLOYMENT.modal.run',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'streaming'],
    docsUrl: 'https://modal.com/docs',
    status: 'metadata-only',
    notes: 'Self-hosted endpoints exposed via Modal Functions.',
    models: [
      { id: 'custom', display: 'Custom Modal endpoint', context: null, in: null, out: null, capabilities: ['chat'], status: 'GA', tags: ['custom'] },
    ],
  },
  {
    id: 'lambda-labs',
    name: 'Lambda Labs Inference',
    category: 'serverless',
    format: 'openai-compatible',
    baseUrl: 'https://api.lambdalabs.com/v1',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'streaming'],
    docsUrl: 'https://docs.lambdalabs.com/inference',
    status: 'metadata-only',
    models: [
      { id: 'llama-4-70b-instruct', display: 'Llama 4 70B Instruct', context: 128000, in: 0.45, out: 0.45, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['gpu'] },
      { id: 'qwen-3-72b-instruct', display: 'Qwen3 72B Instruct', context: 128000, in: 0.5, out: 0.5, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['gpu'] },
    ],
  },
  {
    id: 'baseten',
    name: 'Baseten',
    category: 'serverless',
    format: 'openai-compatible',
    baseUrl: 'https://app.baseten.co/v1',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'streaming'],
    docsUrl: 'https://docs.baseten.co',
    status: 'metadata-only',
    models: [
      { id: 'llama-4-70b-instruct', display: 'Llama 4 70B Instruct', context: 128000, in: 0.5, out: 0.5, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['gpu'] },
    ],
  },
  {
    id: 'cerebras',
    name: 'Cerebras Inference',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.cerebras.ai/v1',
    authType: 'bearer',
    capabilities: ['chat', 'tools', 'streaming'],
    docsUrl: 'https://inference-docs.cerebras.ai',
    status: 'implemented',
    models: [
      { id: 'llama-4-70b', display: 'Llama 4 70B (Wafer-Scale)', context: 128000, in: 0.6, out: 0.6, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['fast'] },
      { id: 'llama-4-405b', display: 'Llama 4 405B (Wafer-Scale)', context: 128000, in: 1.6, out: 2.4, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['fast'] },
    ],
  },
  {
    id: 'sambanova',
    name: 'SambaNova Cloud',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.sambanova.ai/v1',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://docs.sambanova.ai/cloud',
    status: 'implemented',
    models: [
      { id: 'Meta-Llama-4-405B-Instruct', display: 'Llama 4 405B Instruct', context: 128000, in: 1.5, out: 1.5, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['open'] },
      { id: 'Meta-Llama-4-70B-Instruct', display: 'Llama 4 70B Instruct', context: 128000, in: 0.4, out: 0.4, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['fast'] },
    ],
  },
  {
    id: 'nvidia-nim',
    name: 'NVIDIA NIM',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'tools', 'streaming'],
    docsUrl: 'https://docs.nvidia.com/nim',
    status: 'implemented',
    models: [
      { id: 'meta/llama-4-405b-instruct', display: 'Llama 4 405B Instruct', context: 128000, in: 1.5, out: 1.5, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['open'] },
      { id: 'mistralai/mistral-large-3', display: 'Mistral Large 3', context: 256000, in: 2, out: 6, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['frontier'] },
    ],
  },
  {
    id: 'octoai',
    name: 'OctoAI (legacy)',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://text.octoai.run/v1',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://octo.ai',
    status: 'metadata-only',
    notes: 'OctoAI was acquired in 2024; entry kept for legacy migrations.',
    models: [
      { id: 'meta-llama-3-70b-instruct', display: 'Llama 3 70B Instruct', context: 8000, in: 0.5, out: 0.5, capabilities: ['chat', 'streaming'], status: 'legacy', tags: ['legacy'] },
    ],
  },
  {
    id: 'anyscale',
    name: 'Anyscale Endpoints (legacy)',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.endpoints.anyscale.com/v1',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://docs.anyscale.com',
    status: 'metadata-only',
    notes: 'Public endpoints retired; Anyscale platform itself is still active for self-hosted clusters.',
    models: [
      { id: 'meta-llama/Llama-3-70B-Instruct', display: 'Llama 3 70B Instruct', context: 8000, in: 0.5, out: 0.5, capabilities: ['chat', 'streaming'], status: 'legacy', tags: ['legacy'] },
    ],
  },
  {
    id: 'lepton',
    name: 'Lepton AI',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.lepton.run/v1',
    authType: 'bearer',
    capabilities: ['chat', 'image', 'streaming'],
    docsUrl: 'https://www.lepton.ai/docs',
    status: 'metadata-only',
    models: [
      { id: 'llama-4-70b-instruct', display: 'Llama 4 70B Instruct', context: 128000, in: 0.5, out: 0.5, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['open'] },
    ],
  },
  {
    id: 'nebius',
    name: 'Nebius AI Studio',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.studio.nebius.ai/v1',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'streaming'],
    docsUrl: 'https://docs.nebius.ai/studio',
    status: 'implemented',
    models: [
      { id: 'meta-llama/Llama-4-405B-Instruct', display: 'Llama 4 405B Instruct', context: 128000, in: 1.4, out: 1.4, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['open'] },
      { id: 'Qwen/Qwen3-72B-Instruct', display: 'Qwen3 72B Instruct', context: 128000, in: 0.5, out: 0.5, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['open'] },
    ],
  },
  {
    id: 'scaleway',
    name: 'Scaleway Generative APIs',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.scaleway.ai/v1',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'streaming'],
    docsUrl: 'https://www.scaleway.com/en/docs/generative-apis',
    status: 'metadata-only',
    models: [
      { id: 'llama-4-70b-instruct', display: 'Llama 4 70B Instruct', context: 128000, in: 0.45, out: 0.45, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['eu'] },
      { id: 'mistral-large-3', display: 'Mistral Large 3', context: 256000, in: 2, out: 6, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['eu'] },
    ],
  },
  {
    id: 'moonshot',
    name: 'Moonshot AI',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.moonshot.ai/v1',
    authType: 'bearer',
    capabilities: ['chat', 'tools', 'streaming'],
    docsUrl: 'https://platform.moonshot.ai/docs',
    status: 'implemented',
    models: [
      { id: 'kimi-k2.6', display: 'Kimi K2.6', context: 256000, in: 1.2, out: 3.6, capabilities: ['chat', 'tools', 'streaming'], status: 'latest', tags: ['frontier', 'agentic'] },
      { id: 'kimi-k2-turbo-preview', display: 'Kimi K2 Turbo Preview', context: 256000, in: 1.2, out: 3.6, capabilities: ['chat', 'tools', 'streaming'], status: 'preview', tags: ['fast', 'agentic'] },
      { id: 'kimi-k2-0905-preview', display: 'Kimi K2 0905 Preview', context: 256000, in: 1.0, out: 3.0, capabilities: ['chat', 'tools', 'streaming'], status: 'preview', tags: ['agentic'] },
      { id: 'kimi-k2-0711-preview', display: 'Kimi K2 0711 Preview', context: 128000, in: 1.0, out: 3.0, capabilities: ['chat', 'tools', 'streaming'], status: 'legacy', tags: ['agentic'] },
      { id: 'moonshot-v1-128k', display: 'Moonshot v1 128K', context: 128000, in: 1.0, out: 3.0, capabilities: ['chat', 'tools', 'streaming'], status: 'stable', tags: ['long-context'] },
      { id: 'moonshot-v1-32k', display: 'Moonshot v1 32K', context: 32000, in: 0.5, out: 1.5, capabilities: ['chat', 'streaming'], status: 'stable', tags: ['long-context'] },
      { id: 'moonshot-v1-8k', display: 'Moonshot v1 8K', context: 8000, in: 0.2, out: 1.0, capabilities: ['chat', 'streaming'], status: 'stable', tags: ['legacy'] },
    ],
  },
  {
    id: 'xiaomi-mimo',
    name: 'Xiaomi MiMo',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.mimo.xiaomi.com/v1',
    authType: 'bearer',
    capabilities: ['chat', 'tools', 'streaming'],
    docsUrl: 'https://mimo.xiaomi.com',
    status: 'metadata-only',
    notes: 'Public hosted API availability is region-dependent; open-model IDs are included for provider/aggregator mapping.',
    models: [
      { id: 'XiaomiMiMo/MiMo-7B-RL', display: 'MiMo 7B RL', context: 128000, in: 0.2, out: 0.6, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['reasoning', 'open-model'] },
      { id: 'XiaomiMiMo/MiMo-7B-RL-Zero', display: 'MiMo 7B RL Zero', context: 128000, in: 0.2, out: 0.6, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['reasoning', 'open-model'] },
      { id: 'XiaomiMiMo/MiMo-7B-SFT', display: 'MiMo 7B SFT', context: 128000, in: 0.2, out: 0.6, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['open-model'] },
      { id: 'XiaomiMiMo/MiMo-7B-Base', display: 'MiMo 7B Base', context: 128000, in: 0.2, out: 0.6, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['base', 'open-model'] },
    ],
  },
  {
    id: 'ovhcloud',
    name: 'OVHcloud AI Endpoints',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://endpoints.ai.cloud.ovh.net/v1',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'streaming'],
    docsUrl: 'https://help.ovhcloud.com/csm/en-public-cloud-ai-endpoints',
    status: 'metadata-only',
    models: [
      { id: 'llama-4-70b-instruct', display: 'Llama 4 70B Instruct', context: 128000, in: 0.5, out: 0.5, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['eu'] },
    ],
  },
  {
    id: 'ibm-watsonx',
    name: 'IBM watsonx.ai',
    category: 'cloud',
    format: 'native',
    baseUrl: 'https://us-south.ml.cloud.ibm.com',
    authType: 'iam',
    capabilities: ['chat', 'embeddings', 'streaming'],
    docsUrl: 'https://www.ibm.com/products/watsonx-ai',
    status: 'metadata-only',
    notes: 'Requires IAM auth; project_id and region must be set.',
    models: [
      { id: 'ibm/granite-3-8b-instruct', display: 'Granite 3 8B Instruct', context: 32000, in: 0.2, out: 0.4, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['enterprise'] },
      { id: 'meta-llama/llama-4-70b-instruct', display: 'Llama 4 70B Instruct', context: 128000, in: 0.6, out: 0.6, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['enterprise'] },
    ],
  },
  {
    id: 'oracle-oci',
    name: 'Oracle OCI Generative AI',
    category: 'cloud',
    format: 'native',
    baseUrl: 'https://inference.generativeai.us-chicago-1.oci.oraclecloud.com',
    authType: 'oci',
    capabilities: ['chat', 'embeddings', 'streaming'],
    docsUrl: 'https://docs.oracle.com/en-us/iaas/Content/generative-ai/home.htm',
    status: 'metadata-only',
    notes: 'Requires OCI request signing.',
    models: [
      { id: 'cohere.command-a-2026', display: 'Command A (OCI)', context: 256000, in: 1.5, out: 6, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['enterprise'] },
    ],
  },
  {
    id: 'databricks',
    name: 'Databricks Mosaic AI',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://YOUR-WORKSPACE.cloud.databricks.com/serving-endpoints',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'streaming'],
    docsUrl: 'https://docs.databricks.com/en/machine-learning/foundation-models',
    status: 'metadata-only',
    notes: 'Requires a Databricks workspace and serving endpoint.',
    models: [
      { id: 'databricks-dbrx-2', display: 'DBRX-2', context: 32000, in: 0.75, out: 2.25, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['enterprise'] },
    ],
  },
  {
    id: 'snowflake-cortex',
    name: 'Snowflake Cortex',
    category: 'cloud',
    format: 'native',
    baseUrl: 'https://YOUR-ACCOUNT.snowflakecomputing.com',
    authType: 'oauth',
    capabilities: ['chat', 'embeddings'],
    docsUrl: 'https://docs.snowflake.com/en/user-guide/snowflake-cortex',
    status: 'metadata-only',
    notes: 'Requires Snowflake account and OAuth flow.',
    models: [
      { id: 'mistral-large-3', display: 'Mistral Large 3 (Cortex)', context: 256000, in: 2, out: 6, capabilities: ['chat'], status: 'GA', tags: ['enterprise'] },
      { id: 'llama-4-70b', display: 'Llama 4 70B (Cortex)', context: 128000, in: 0.6, out: 0.6, capabilities: ['chat'], status: 'GA', tags: ['enterprise'] },
    ],
  },
  {
    id: 'vertex-ai',
    name: 'Google Vertex AI',
    category: 'cloud',
    format: 'native',
    baseUrl: 'https://us-central1-aiplatform.googleapis.com',
    authType: 'gcp',
    capabilities: ['chat', 'embeddings', 'image', 'vision', 'audio', 'tools', 'streaming'],
    docsUrl: 'https://cloud.google.com/vertex-ai/generative-ai',
    status: 'metadata-only',
    notes: 'Requires GCP service account and project_id.',
    models: [
      { id: 'gemini-3.0-pro', display: 'Gemini 3.0 Pro (Vertex)', context: 2000000, in: 2.5, out: 10, capabilities: ['chat', 'vision', 'audio', 'tools', 'streaming'], status: 'GA', tags: ['enterprise'] },
      { id: 'claude-opus-4-5@anthropic', display: 'Claude Opus 4.5 (Vertex)', context: 400000, in: 10, out: 50, capabilities: ['chat', 'vision', 'tools', 'streaming'], status: 'GA', tags: ['enterprise'] },
    ],
  },
  {
    id: 'github-models',
    name: 'GitHub Models',
    category: 'aggregator',
    format: 'openai-compatible',
    baseUrl: 'https://models.inference.ai.azure.com',
    authType: 'bearer',
    capabilities: ['chat', 'tools', 'streaming'],
    docsUrl: 'https://github.com/marketplace/models',
    status: 'implemented',
    notes: 'Authenticate with a GitHub PAT.',
    models: [
      { id: 'gpt-5-mini', display: 'GPT-5 Mini (GitHub)', context: 200000, in: 0.3, out: 1.2, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['github'] },
      { id: 'meta-llama-4-405b-instruct', display: 'Llama 4 405B Instruct (GitHub)', context: 128000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['github'] },
    ],
  },
  {
    id: 'gitlab-duo',
    name: 'GitLab Duo (Code Suggestions)',
    category: 'aggregator',
    format: 'native',
    baseUrl: 'https://gitlab.com/api/v4/code_suggestions',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://docs.gitlab.com/ee/user/gitlab_duo/',
    status: 'metadata-only',
    notes: 'Limited to authorized GitLab Duo seats.',
    models: [
      { id: 'duo-default', display: 'Duo Default', context: 32000, in: null, out: null, capabilities: ['chat'], status: 'GA', tags: ['code'] },
    ],
  },

  // 2) Local runtimes
  {
    id: 'ollama',
    name: 'Ollama (local)',
    category: 'local',
    format: 'openai-compatible',
    baseUrl: 'http://localhost:11434/v1',
    authType: 'none',
    capabilities: ['chat', 'embeddings', 'streaming', 'vision'],
    docsUrl: 'https://github.com/ollama/ollama/blob/main/docs/openai.md',
    status: 'implemented',
    models: [
      { id: 'llama4', display: 'Llama 4 (local)', context: 128000, in: 0, out: 0, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['local'] },
      { id: 'qwen3-coder', display: 'Qwen3 Coder (local)', context: 128000, in: 0, out: 0, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['local', 'code'] },
      { id: 'deepseek-r2', display: 'DeepSeek R2 (local)', context: 128000, in: 0, out: 0, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['local', 'reasoning'] },
      { id: 'gemma-3-27b', display: 'Gemma 3 27B (local)', context: 128000, in: 0, out: 0, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['local'] },
    ],
  },
  {
    id: 'lmstudio',
    name: 'LM Studio (local)',
    category: 'local',
    format: 'openai-compatible',
    baseUrl: 'http://localhost:1234/v1',
    authType: 'none',
    capabilities: ['chat', 'embeddings', 'streaming'],
    docsUrl: 'https://lmstudio.ai/docs',
    status: 'implemented',
    models: [
      { id: 'auto', display: 'Currently loaded model', context: null, in: 0, out: 0, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['local'] },
    ],
  },
  {
    id: 'vllm',
    name: 'vLLM (self-hosted)',
    category: 'local',
    format: 'openai-compatible',
    baseUrl: 'http://localhost:8000/v1',
    authType: 'optional-bearer',
    capabilities: ['chat', 'embeddings', 'streaming', 'tools'],
    docsUrl: 'https://docs.vllm.ai',
    status: 'implemented',
    models: [
      { id: 'auto', display: 'Currently served model', context: null, in: 0, out: 0, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['local'] },
    ],
  },
  {
    id: 'llama-cpp',
    name: 'llama.cpp server',
    category: 'local',
    format: 'openai-compatible',
    baseUrl: 'http://localhost:8080/v1',
    authType: 'none',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md',
    status: 'implemented',
    models: [
      { id: 'auto', display: 'Currently loaded gguf', context: null, in: 0, out: 0, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['local'] },
    ],
  },
  {
    id: 'tgi',
    name: 'Text Generation Inference (TGI)',
    category: 'local',
    format: 'openai-compatible',
    baseUrl: 'http://localhost:8080/v1',
    authType: 'optional-bearer',
    capabilities: ['chat', 'embeddings', 'streaming'],
    docsUrl: 'https://huggingface.co/docs/text-generation-inference',
    status: 'implemented',
    models: [
      { id: 'auto', display: 'Currently served TGI model', context: null, in: 0, out: 0, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['local'] },
    ],
  },
  {
    id: 'localai',
    name: 'LocalAI',
    category: 'local',
    format: 'openai-compatible',
    baseUrl: 'http://localhost:8080/v1',
    authType: 'none',
    capabilities: ['chat', 'embeddings', 'image', 'audio', 'streaming'],
    docsUrl: 'https://localai.io/',
    status: 'implemented',
    models: [
      { id: 'auto', display: 'LocalAI default', context: null, in: 0, out: 0, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['local'] },
    ],
  },
  {
    id: 'litellm-proxy',
    name: 'LiteLLM Proxy',
    category: 'aggregator',
    format: 'openai-compatible',
    baseUrl: 'http://localhost:4000/v1',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'streaming', 'tools'],
    docsUrl: 'https://docs.litellm.ai/docs/proxy/quick_start',
    status: 'implemented',
    models: [
      { id: 'router', display: 'LiteLLM router', context: null, in: null, out: null, capabilities: ['chat'], status: 'GA', tags: ['router'] },
    ],
  },
  {
    id: 'anyscale-compatible',
    name: 'AnyScale-compatible endpoint',
    category: 'aggregator',
    format: 'openai-compatible',
    baseUrl: 'https://YOUR-ENDPOINT/v1',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: '',
    status: 'metadata-only',
    notes: 'Generic OpenAI-compatible endpoint shape used by many self-hosted clusters.',
    models: [
      { id: 'auto', display: 'Auto', context: null, in: null, out: null, capabilities: ['chat'], status: 'GA', tags: ['custom'] },
    ],
  },
  {
    id: 'openai-compatible-custom',
    name: 'Custom OpenAI-compatible',
    category: 'custom',
    format: 'openai-compatible',
    baseUrl: 'https://YOUR-PROVIDER/v1',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'streaming'],
    docsUrl: '',
    status: 'implemented',
    notes: 'Use this entry for any provider that implements an OpenAI-style /v1 API.',
    models: [
      { id: 'auto', display: 'Default model', context: null, in: null, out: null, capabilities: ['chat'], status: 'GA', tags: ['custom'] },
    ],
  },
  {
    id: 'anthropic-compatible-custom',
    name: 'Custom Anthropic-compatible',
    category: 'custom',
    format: 'anthropic-compatible',
    baseUrl: 'https://YOUR-PROVIDER',
    authType: 'x-api-key',
    capabilities: ['chat', 'streaming'],
    docsUrl: '',
    status: 'implemented',
    notes: 'For self-hosted Anthropic-shaped APIs.',
    models: [
      { id: 'auto', display: 'Default model', context: null, in: null, out: null, capabilities: ['chat'], status: 'GA', tags: ['custom'] },
    ],
  },
  {
    id: 'http-custom',
    name: 'Custom HTTP provider',
    category: 'custom',
    format: 'native',
    baseUrl: 'https://YOUR-PROVIDER',
    authType: 'custom',
    capabilities: ['chat'],
    docsUrl: '',
    status: 'metadata-only',
    notes: 'Free-form HTTP endpoint. Use with a custom adapter.',
    models: [
      { id: 'auto', display: 'Default model', context: null, in: null, out: null, capabilities: ['chat'], status: 'planned', tags: ['custom'] },
    ],
  },

  // 3) Image / multimodal
  {
    id: 'stability',
    name: 'Stability AI',
    category: 'image',
    format: 'native',
    baseUrl: 'https://api.stability.ai',
    authType: 'bearer',
    capabilities: ['image'],
    docsUrl: 'https://platform.stability.ai/docs',
    status: 'metadata-only',
    models: [
      { id: 'stable-diffusion-3.5-ultra', display: 'Stable Diffusion 3.5 Ultra', context: 0, in: null, out: null, capabilities: ['image'], status: 'GA', tags: ['image'] },
    ],
  },
  {
    id: 'leonardo',
    name: 'Leonardo.Ai',
    category: 'image',
    format: 'native',
    baseUrl: 'https://cloud.leonardo.ai/api/rest/v1',
    authType: 'bearer',
    capabilities: ['image'],
    docsUrl: 'https://docs.leonardo.ai',
    status: 'metadata-only',
    models: [
      { id: 'phoenix-1.1', display: 'Phoenix 1.1', context: 0, in: null, out: null, capabilities: ['image'], status: 'GA', tags: ['image'] },
    ],
  },
  {
    id: 'midjourney-api',
    name: 'Midjourney API (community proxy)',
    category: 'image',
    format: 'native',
    baseUrl: 'https://api.midjourney-proxy.example/v1',
    authType: 'bearer',
    capabilities: ['image'],
    docsUrl: '',
    status: 'metadata-only',
    notes: 'Community proxy; verify Midjourney TOS before using.',
    models: [
      { id: 'mj-v7', display: 'Midjourney v7 (proxy)', context: 0, in: null, out: null, capabilities: ['image'], status: 'community', tags: ['image'] },
    ],
  },
  {
    id: 'recraft',
    name: 'Recraft',
    category: 'image',
    format: 'native',
    baseUrl: 'https://external.api.recraft.ai/v1',
    authType: 'bearer',
    capabilities: ['image'],
    docsUrl: 'https://www.recraft.ai/docs',
    status: 'metadata-only',
    models: [
      { id: 'recraft-v3', display: 'Recraft v3', context: 0, in: null, out: null, capabilities: ['image'], status: 'GA', tags: ['image'] },
    ],
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    category: 'image',
    format: 'native',
    baseUrl: 'https://api.ideogram.ai',
    authType: 'api-key',
    capabilities: ['image'],
    docsUrl: 'https://developer.ideogram.ai',
    status: 'metadata-only',
    models: [
      { id: 'ideogram-3', display: 'Ideogram 3', context: 0, in: null, out: null, capabilities: ['image'], status: 'GA', tags: ['image'] },
    ],
  },
  {
    id: 'runway',
    name: 'Runway',
    category: 'image',
    format: 'native',
    baseUrl: 'https://api.runwayml.com/v1',
    authType: 'bearer',
    capabilities: ['image'],
    docsUrl: 'https://docs.runwayml.com',
    status: 'metadata-only',
    models: [
      { id: 'gen-4', display: 'Gen-4', context: 0, in: null, out: null, capabilities: ['image'], status: 'GA', tags: ['video'] },
    ],
  },
  {
    id: 'luma',
    name: 'Luma AI',
    category: 'image',
    format: 'native',
    baseUrl: 'https://api.lumalabs.ai/dream-machine/v1',
    authType: 'bearer',
    capabilities: ['image'],
    docsUrl: 'https://docs.lumalabs.ai',
    status: 'metadata-only',
    models: [
      { id: 'ray-3', display: 'Ray 3', context: 0, in: null, out: null, capabilities: ['image'], status: 'GA', tags: ['video'] },
    ],
  },
  {
    id: 'flux',
    name: 'Black Forest Labs FLUX',
    category: 'image',
    format: 'native',
    baseUrl: 'https://api.bfl.ml/v1',
    authType: 'api-key',
    capabilities: ['image'],
    docsUrl: 'https://docs.bfl.ml',
    status: 'metadata-only',
    models: [
      { id: 'flux-2-pro', display: 'FLUX 2 Pro', context: 0, in: null, out: null, capabilities: ['image'], status: 'GA', tags: ['image'] },
      { id: 'flux-2-dev', display: 'FLUX 2 Dev', context: 0, in: null, out: null, capabilities: ['image'], status: 'GA', tags: ['image'] },
    ],
  },

  // 4) Embedding / rerank specialists
  {
    id: 'voyage',
    name: 'Voyage AI',
    category: 'embeddings',
    format: 'native',
    baseUrl: 'https://api.voyageai.com/v1',
    authType: 'bearer',
    capabilities: ['embeddings', 'rerank'],
    docsUrl: 'https://docs.voyageai.com',
    status: 'metadata-only',
    models: [
      { id: 'voyage-3.5', display: 'Voyage 3.5', context: 32000, in: 0.06, out: 0, capabilities: ['embeddings'], status: 'GA', tags: ['embedding'] },
      { id: 'rerank-3', display: 'Rerank 3', context: 8000, in: 0.5, out: 0, capabilities: ['rerank'], status: 'GA', tags: ['rerank'] },
    ],
  },
  {
    id: 'jina',
    name: 'Jina AI',
    category: 'embeddings',
    format: 'native',
    baseUrl: 'https://api.jina.ai/v1',
    authType: 'bearer',
    capabilities: ['embeddings', 'rerank'],
    docsUrl: 'https://jina.ai/embeddings',
    status: 'metadata-only',
    models: [
      { id: 'jina-embeddings-v4', display: 'Jina Embeddings v4', context: 8192, in: 0.05, out: 0, capabilities: ['embeddings'], status: 'GA', tags: ['embedding'] },
      { id: 'jina-reranker-v3', display: 'Jina Reranker v3', context: 8192, in: 0.4, out: 0, capabilities: ['rerank'], status: 'GA', tags: ['rerank'] },
    ],
  },
  {
    id: 'nomic',
    name: 'Nomic',
    category: 'embeddings',
    format: 'native',
    baseUrl: 'https://api-atlas.nomic.ai/v1',
    authType: 'bearer',
    capabilities: ['embeddings'],
    docsUrl: 'https://docs.nomic.ai',
    status: 'metadata-only',
    models: [
      { id: 'nomic-embed-text-v2', display: 'Nomic Embed Text v2', context: 8192, in: 0.02, out: 0, capabilities: ['embeddings'], status: 'GA', tags: ['embedding'] },
    ],
  },
  {
    id: 'mixedbread',
    name: 'Mixedbread',
    category: 'embeddings',
    format: 'native',
    baseUrl: 'https://api.mixedbread.com/v1',
    authType: 'bearer',
    capabilities: ['embeddings', 'rerank'],
    docsUrl: 'https://www.mixedbread.com/docs',
    status: 'metadata-only',
    models: [
      { id: 'mxbai-embed-large-v2', display: 'mxbai Embed Large v2', context: 8192, in: 0.05, out: 0, capabilities: ['embeddings'], status: 'GA', tags: ['embedding'] },
      { id: 'mxbai-rerank-large-v2', display: 'mxbai Rerank Large v2', context: 8192, in: 0.45, out: 0, capabilities: ['rerank'], status: 'GA', tags: ['rerank'] },
    ],
  },

  // 5) Speech
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    category: 'audio',
    format: 'native',
    baseUrl: 'https://api.elevenlabs.io/v1',
    authType: 'xi-api-key',
    capabilities: ['audio'],
    docsUrl: 'https://elevenlabs.io/docs/api-reference',
    status: 'metadata-only',
    models: [
      { id: 'eleven_v3', display: 'Eleven v3', context: 0, in: null, out: null, capabilities: ['audio'], status: 'GA', tags: ['tts'] },
    ],
  },
  {
    id: 'deepgram',
    name: 'Deepgram',
    category: 'audio',
    format: 'native',
    baseUrl: 'https://api.deepgram.com/v1',
    authType: 'token',
    capabilities: ['audio'],
    docsUrl: 'https://developers.deepgram.com',
    status: 'metadata-only',
    models: [
      { id: 'nova-3', display: 'Nova 3 (STT)', context: 0, in: null, out: null, capabilities: ['audio'], status: 'GA', tags: ['stt'] },
    ],
  },
  {
    id: 'assemblyai',
    name: 'AssemblyAI',
    category: 'audio',
    format: 'native',
    baseUrl: 'https://api.assemblyai.com',
    authType: 'authorization',
    capabilities: ['audio'],
    docsUrl: 'https://www.assemblyai.com/docs',
    status: 'metadata-only',
    models: [
      { id: 'universal-2', display: 'Universal-2 STT', context: 0, in: null, out: null, capabilities: ['audio'], status: 'GA', tags: ['stt'] },
    ],
  },
  {
    id: 'cartesia',
    name: 'Cartesia',
    category: 'audio',
    format: 'native',
    baseUrl: 'https://api.cartesia.ai',
    authType: 'bearer',
    capabilities: ['audio'],
    docsUrl: 'https://docs.cartesia.ai',
    status: 'metadata-only',
    models: [
      { id: 'sonic-2', display: 'Sonic 2 (TTS)', context: 0, in: null, out: null, capabilities: ['audio'], status: 'GA', tags: ['tts'] },
    ],
  },

  // 6) Additional cloud LLM providers
  {
    id: 'reka',
    name: 'Reka',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.reka.ai/v1',
    authType: 'bearer',
    capabilities: ['chat', 'vision', 'streaming'],
    docsUrl: 'https://docs.reka.ai',
    status: 'metadata-only',
    models: [
      { id: 'reka-flash-3', display: 'Reka Flash 3', context: 128000, in: 0.5, out: 1.5, capabilities: ['chat', 'vision', 'streaming'], status: 'GA', tags: ['multimodal'] },
      { id: 'reka-core-3', display: 'Reka Core 3', context: 256000, in: 3, out: 12, capabilities: ['chat', 'vision', 'streaming'], status: 'GA', tags: ['frontier'] },
    ],
  },
  {
    id: 'ai21',
    name: 'AI21 Labs',
    category: 'cloud',
    format: 'native',
    baseUrl: 'https://api.ai21.com/studio/v1',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'streaming'],
    docsUrl: 'https://docs.ai21.com',
    status: 'metadata-only',
    models: [
      { id: 'jamba-2-large', display: 'Jamba 2 Large', context: 256000, in: 2, out: 8, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['mamba'] },
      { id: 'jamba-2-mini', display: 'Jamba 2 Mini', context: 256000, in: 0.2, out: 0.4, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['mamba'] },
    ],
  },
  {
    id: 'aleph-alpha',
    name: 'Aleph Alpha',
    category: 'cloud',
    format: 'native',
    baseUrl: 'https://api.aleph-alpha.com',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings'],
    docsUrl: 'https://docs.aleph-alpha.com',
    status: 'metadata-only',
    models: [
      { id: 'pharia-1-7b-control', display: 'Pharia 1 7B Control', context: 32000, in: 0.5, out: 1.5, capabilities: ['chat'], status: 'GA', tags: ['eu'] },
    ],
  },
  {
    id: 'mistral-azure',
    name: 'Mistral on Azure AI Studio',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://YOUR-RESOURCE.eastus.models.ai.azure.com/v1',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://learn.microsoft.com/azure/ai-studio/how-to/deploy-models-mistral',
    status: 'metadata-only',
    models: [
      { id: 'mistral-large-3', display: 'Mistral Large 3 (Azure)', context: 256000, in: 2, out: 6, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['enterprise'] },
    ],
  },
  {
    id: 'inflection',
    name: 'Inflection AI',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.inflection.ai/v1',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://developers.inflection.ai',
    status: 'metadata-only',
    models: [
      { id: 'inflection-3-pi', display: 'Inflection 3 Pi', context: 32000, in: 1, out: 5, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['assistant'] },
    ],
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.minimax.chat/v1',
    authType: 'bearer',
    capabilities: ['chat', 'audio', 'streaming'],
    docsUrl: 'https://www.minimax.io/api-doc',
    status: 'metadata-only',
    models: [
      { id: 'MiniMax-M1', display: 'MiniMax M1', context: 1000000, in: 0.6, out: 2.4, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['frontier', 'reasoning', 'agent'] },
      { id: 'MiniMax-Text-01', display: 'MiniMax Text 01', context: 1000000, in: 0.4, out: 1.2, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['long-context'] },
      { id: 'MiniMax-VL-01', display: 'MiniMax VL 01', context: 256000, in: 0.4, out: 1.2, capabilities: ['chat', 'vision', 'streaming'], status: 'GA', tags: ['vision', 'multimodal'] },
      { id: 'minimax-m2', display: 'MiniMax M2', context: 1000000, in: 0.6, out: 2.4, capabilities: ['chat', 'tools', 'streaming'], status: 'legacy', tags: ['agent'] },
      { id: 'minimax-voice-01', display: 'MiniMax Voice 01', context: 128000, in: null, out: null, capabilities: ['audio', 'streaming'], status: 'GA', tags: ['voice'] },
      { id: 'abab6.5s-chat', display: 'abab6.5s Chat', context: 245760, in: 0.3, out: 0.9, capabilities: ['chat', 'streaming'], status: 'legacy', tags: ['cn'] },
    ],
  },
  {
    id: 'zhipu',
    name: 'Zhipu AI (BigModel)',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'tools', 'streaming'],
    docsUrl: 'https://open.bigmodel.cn/dev/api',
    status: 'metadata-only',
    models: [
      { id: 'glm-5', display: 'GLM-5', context: 256000, in: 1.2, out: 3.6, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['frontier', 'cn'] },
      { id: 'glm-5-air', display: 'GLM-5 Air', context: 128000, in: 0.2, out: 0.6, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['cn', 'cheap'] },
      { id: 'glm-4.6', display: 'GLM-4.6', context: 200000, in: 0.8, out: 2.4, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['stable'] },
      { id: 'glm-4.5', display: 'GLM-4.5', context: 128000, in: 0.5, out: 1.5, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['legacy'] },
    ],
  },
  {
    id: 'baidu-qianfan',
    name: 'Baidu Qianfan (ERNIE)',
    category: 'cloud',
    format: 'native',
    baseUrl: 'https://qianfan.baidubce.com',
    authType: 'oauth',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://cloud.baidu.com/doc/WENXINWORKSHOP',
    status: 'metadata-only',
    models: [
      { id: 'ernie-5.0', display: 'ERNIE 5.0', context: 128000, in: 1.5, out: 4.5, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['cn'] },
    ],
  },
  {
    id: 'tencent-hunyuan',
    name: 'Tencent Hunyuan',
    category: 'cloud',
    format: 'native',
    baseUrl: 'https://hunyuan.tencentcloudapi.com',
    authType: 'tencent-cloud',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://cloud.tencent.com/document/product/1729',
    status: 'metadata-only',
    models: [
      { id: 'hunyuan-pro-3', display: 'Hunyuan Pro 3', context: 128000, in: 1.2, out: 3.6, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['cn'] },
    ],
  },
  {
    id: 'alibaba-dashscope',
    name: 'Alibaba DashScope (Qwen)',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'tools', 'streaming'],
    docsUrl: 'https://help.aliyun.com/zh/dashscope/',
    status: 'implemented',
    models: [
      { id: 'qwen-max', display: 'Qwen Max', context: 1000000, in: 2, out: 6, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['frontier', 'cn'] },
      { id: 'qwen-max-latest', display: 'Qwen Max Latest', context: 1000000, in: 2, out: 6, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['frontier', 'cn'] },
      { id: 'qwen-plus', display: 'Qwen Plus', context: 1000000, in: 0.4, out: 1.2, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['cn'] },
      { id: 'qwen-turbo', display: 'Qwen Turbo', context: 1000000, in: 0.05, out: 0.2, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['fast', 'cheap'] },
      { id: 'qwen-long', display: 'Qwen Long', context: 10000000, in: 0.02, out: 0.2, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['long-context'] },
      { id: 'qwen3-235b-a22b', display: 'Qwen3 235B A22B', context: 262144, in: 0.6, out: 2.4, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['open'] },
      { id: 'qwen3-32b', display: 'Qwen3 32B', context: 131072, in: 0.2, out: 0.8, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['open'] },
      { id: 'qwen3-coder-plus', display: 'Qwen3 Coder Plus', context: 1000000, in: 0.4, out: 1.2, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['code'] },
      { id: 'qwen-vl-max', display: 'Qwen VL Max', context: 128000, in: 1.0, out: 3.0, capabilities: ['chat', 'vision', 'streaming'], status: 'GA', tags: ['vision'] },
      { id: 'qwen-vl-plus', display: 'Qwen VL Plus', context: 128000, in: 0.25, out: 0.75, capabilities: ['chat', 'vision', 'streaming'], status: 'GA', tags: ['vision'] },
    ],
  },
  {
    id: 'yandex-foundation',
    name: 'Yandex Foundation Models',
    category: 'cloud',
    format: 'native',
    baseUrl: 'https://llm.api.cloud.yandex.net',
    authType: 'iam',
    capabilities: ['chat', 'embeddings'],
    docsUrl: 'https://yandex.cloud/en/docs/foundation-models/',
    status: 'metadata-only',
    models: [
      { id: 'yandex-gpt-5', display: 'YandexGPT 5', context: 32000, in: null, out: null, capabilities: ['chat'], status: 'GA', tags: ['ru'] },
    ],
  },
  {
    id: 'sber-gigachat',
    name: 'Sber GigaChat',
    category: 'cloud',
    format: 'native',
    baseUrl: 'https://gigachat.devices.sberbank.ru',
    authType: 'oauth',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://developers.sber.ru/docs/ru/gigachat/api/overview',
    status: 'metadata-only',
    models: [
      { id: 'GigaChat-Pro-3', display: 'GigaChat Pro 3', context: 32000, in: null, out: null, capabilities: ['chat'], status: 'GA', tags: ['ru'] },
    ],
  },
  {
    id: 'huawei-pangu',
    name: 'Huawei Pangu',
    category: 'cloud',
    format: 'native',
    baseUrl: 'https://pangu.huaweicloud.com',
    authType: 'iam',
    capabilities: ['chat'],
    docsUrl: 'https://support.huaweicloud.com/intl/en-us/pangu/',
    status: 'metadata-only',
    models: [
      { id: 'pangu-5-l', display: 'Pangu 5 L', context: 32000, in: null, out: null, capabilities: ['chat'], status: 'GA', tags: ['cn'] },
    ],
  },
  {
    id: 'naver-hyperclova',
    name: 'Naver HyperCLOVA X',
    category: 'cloud',
    format: 'native',
    baseUrl: 'https://clovastudio.stream.ntruss.com',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://www.ncloud.com/product/aiService/clovaStudio',
    status: 'metadata-only',
    models: [
      { id: 'HCX-005', display: 'HyperCLOVA X 005', context: 128000, in: null, out: null, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['kr'] },
    ],
  },
  {
    id: 'upstage',
    name: 'Upstage',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.upstage.ai/v1/solar',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'streaming'],
    docsUrl: 'https://developers.upstage.ai',
    status: 'metadata-only',
    models: [
      { id: 'solar-3-pro', display: 'Solar 3 Pro', context: 64000, in: 0.7, out: 1.4, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['kr'] },
    ],
  },
  {
    id: 'sea-lion',
    name: 'AISG Sea-Lion',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.sea-lion.ai/v1',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://aisingapore.org/sea-lion/',
    status: 'metadata-only',
    models: [
      { id: 'sea-lion-v3', display: 'Sea-Lion v3', context: 32000, in: null, out: null, capabilities: ['chat'], status: 'GA', tags: ['sea'] },
    ],
  },
  {
    id: 'sarvam',
    name: 'Sarvam AI',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.sarvam.ai/v1',
    authType: 'bearer',
    capabilities: ['chat', 'audio', 'streaming'],
    docsUrl: 'https://docs.sarvam.ai',
    status: 'metadata-only',
    models: [
      { id: 'sarvam-2', display: 'Sarvam 2', context: 32000, in: null, out: null, capabilities: ['chat', 'audio'], status: 'GA', tags: ['in'] },
    ],
  },
  {
    id: 'krutrim',
    name: 'Ola Krutrim',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://cloud.olakrutrim.com/v1',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://docs.olakrutrim.com',
    status: 'metadata-only',
    models: [
      { id: 'krutrim-3', display: 'Krutrim 3', context: 64000, in: null, out: null, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['in'] },
    ],
  },
  {
    id: 'inception',
    name: 'Inception Labs',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.inceptionlabs.ai/v1',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://www.inceptionlabs.ai/',
    status: 'metadata-only',
    models: [
      { id: 'mercury-coder', display: 'Mercury Coder (Diffusion LLM)', context: 32000, in: 0.3, out: 0.9, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['diffusion-llm'] },
    ],
  },
  {
    id: 'tii-falcon',
    name: 'TII Falcon Cloud',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://falcon.tii.ae/v1',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://falconllm.tii.ae',
    status: 'metadata-only',
    models: [
      { id: 'falcon-3-180b', display: 'Falcon 3 180B', context: 32000, in: 1.5, out: 1.5, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['ae'] },
    ],
  },
  {
    id: 'novita',
    name: 'Novita AI',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.novita.ai/v3/openai',
    authType: 'bearer',
    capabilities: ['chat', 'image', 'streaming'],
    docsUrl: 'https://novita.ai/docs',
    status: 'implemented',
    models: [
      { id: 'meta-llama/llama-4-70b-instruct', display: 'Llama 4 70B Instruct', context: 128000, in: 0.4, out: 0.4, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['open'] },
    ],
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.siliconflow.cn/v1',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'streaming'],
    docsUrl: 'https://docs.siliconflow.cn',
    status: 'implemented',
    models: [
      { id: 'Qwen/Qwen3-72B-Instruct', display: 'Qwen3 72B Instruct', context: 128000, in: 0.4, out: 0.4, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['cn'] },
    ],
  },
  {
    id: 'deepinfra',
    name: 'DeepInfra',
    category: 'serverless',
    format: 'openai-compatible',
    baseUrl: 'https://api.deepinfra.com/v1/openai',
    authType: 'bearer',
    capabilities: ['chat', 'embeddings', 'image', 'streaming'],
    docsUrl: 'https://deepinfra.com/docs',
    status: 'implemented',
    models: [
      { id: 'meta-llama/Llama-4-70B-Instruct', display: 'Llama 4 70B Instruct', context: 128000, in: 0.4, out: 0.4, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['open'] },
    ],
  },
  {
    id: 'octo-genai',
    name: 'OctoML GenAI',
    category: 'serverless',
    format: 'openai-compatible',
    baseUrl: 'https://api.octoai.cloud/v1',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: '',
    status: 'metadata-only',
    notes: 'Successor to OctoAI text endpoints, post-acquisition.',
    models: [
      { id: 'meta-llama-4-70b-instruct', display: 'Llama 4 70B Instruct', context: 128000, in: null, out: null, capabilities: ['chat'], status: 'GA', tags: ['open'] },
    ],
  },
  {
    id: 'runpod',
    name: 'RunPod Serverless',
    category: 'serverless',
    format: 'openai-compatible',
    baseUrl: 'https://api.runpod.ai/v2',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://docs.runpod.io',
    status: 'metadata-only',
    models: [
      { id: 'auto', display: 'Custom RunPod endpoint', context: null, in: null, out: null, capabilities: ['chat'], status: 'GA', tags: ['gpu'] },
    ],
  },
  {
    id: 'beam-cloud',
    name: 'Beam',
    category: 'serverless',
    format: 'openai-compatible',
    baseUrl: 'https://YOUR-DEPLOYMENT.beam.cloud',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://docs.beam.cloud',
    status: 'metadata-only',
    models: [
      { id: 'auto', display: 'Custom Beam endpoint', context: null, in: null, out: null, capabilities: ['chat'], status: 'GA', tags: ['gpu'] },
    ],
  },
  {
    id: 'koyeb',
    name: 'Koyeb Inference',
    category: 'serverless',
    format: 'openai-compatible',
    baseUrl: 'https://api.koyeb.com/v1',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://www.koyeb.com/docs/inference',
    status: 'metadata-only',
    models: [
      { id: 'llama-4-70b-instruct', display: 'Llama 4 70B Instruct', context: 128000, in: 0.5, out: 0.5, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['eu'] },
    ],
  },
  {
    id: 'fly-fks',
    name: 'Fly Inference (community)',
    category: 'serverless',
    format: 'openai-compatible',
    baseUrl: 'https://YOUR-APP.fly.dev/v1',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: '',
    status: 'metadata-only',
    notes: 'Generic OpenAI-compatible inference deployed on Fly.io.',
    models: [
      { id: 'auto', display: 'Custom Fly endpoint', context: null, in: null, out: null, capabilities: ['chat'], status: 'GA', tags: ['custom'] },
    ],
  },
  {
    id: 'portkey',
    name: 'Portkey Gateway',
    category: 'aggregator',
    format: 'openai-compatible',
    baseUrl: 'https://api.portkey.ai/v1',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://portkey.ai/docs',
    status: 'metadata-only',
    models: [
      { id: 'auto', display: 'Portkey virtual key', context: null, in: null, out: null, capabilities: ['chat'], status: 'GA', tags: ['router'] },
    ],
  },
  {
    id: 'helicone-gateway',
    name: 'Helicone Gateway',
    category: 'aggregator',
    format: 'openai-compatible',
    baseUrl: 'https://api.helicone.ai/v1/gateway',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://docs.helicone.ai',
    status: 'metadata-only',
    models: [
      { id: 'auto', display: 'Helicone gateway', context: null, in: null, out: null, capabilities: ['chat'], status: 'GA', tags: ['router'] },
    ],
  },
  {
    id: 'vellum',
    name: 'Vellum',
    category: 'aggregator',
    format: 'openai-compatible',
    baseUrl: 'https://api.vellum.ai/v1',
    authType: 'bearer',
    capabilities: ['chat'],
    docsUrl: 'https://docs.vellum.ai',
    status: 'metadata-only',
    models: [
      { id: 'auto', display: 'Vellum workflow', context: null, in: null, out: null, capabilities: ['chat'], status: 'GA', tags: ['workflow'] },
    ],
  },
  {
    id: 'crusoe',
    name: 'Crusoe Cloud',
    category: 'serverless',
    format: 'openai-compatible',
    baseUrl: 'https://inference.crusoe.ai/v1',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://docs.crusoecloud.com',
    status: 'metadata-only',
    models: [
      { id: 'llama-4-70b-instruct', display: 'Llama 4 70B Instruct', context: 128000, in: 0.5, out: 0.5, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['gpu'] },
    ],
  },
  {
    id: 'foundry-local',
    name: 'Foundry Local (custom OpenAI-compatible)',
    category: 'local',
    format: 'openai-compatible',
    baseUrl: 'http://localhost:5000/v1',
    authType: 'none',
    capabilities: ['chat', 'streaming'],
    docsUrl: '',
    status: 'metadata-only',
    notes: 'Generic placeholder for in-house inference servers running on localhost.',
    models: [
      { id: 'auto', display: 'Default model', context: null, in: 0, out: 0, capabilities: ['chat'], status: 'GA', tags: ['local', 'custom'] },
    ],
  },
  {
    id: 'bytedance-doubao',
    name: 'ByteDance Doubao',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    authType: 'bearer',
    capabilities: ['chat', 'tools', 'streaming', 'vision'],
    docsUrl: 'https://www.volcengine.com/docs/82379',
    status: 'metadata-only',
    models: [
      { id: 'doubao-2-pro', display: 'Doubao 2 Pro', context: 256000, in: 0.4, out: 1.2, capabilities: ['chat', 'tools', 'vision', 'streaming'], status: 'GA', tags: ['frontier'] },
      { id: 'doubao-2-lite', display: 'Doubao 2 Lite', context: 128000, in: 0.05, out: 0.15, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['cheap'] },
    ],
  },
  {
    id: 'baichuan',
    name: 'Baichuan AI',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.baichuan-ai.com/v1',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://platform.baichuan-ai.com/docs',
    status: 'metadata-only',
    models: [
      { id: 'baichuan-4', display: 'Baichuan 4', context: 128000, in: 1, out: 4, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['cn'] },
    ],
  },
  {
    id: 'aleph-alpha-pharia',
    name: 'Pharia (Aleph Alpha) - OpenAI bridge',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.aleph-alpha.com/openai/v1',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://docs.aleph-alpha.com',
    status: 'metadata-only',
    models: [
      { id: 'pharia-1-7b-control-openai', display: 'Pharia 1 7B Control (OAI)', context: 32000, in: 0.5, out: 1.5, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['eu'] },
    ],
  },
  {
    id: 'zhipu-glm',
    name: 'Zhipu GLM',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    authType: 'bearer',
    capabilities: ['chat', 'streaming', 'tools'],
    docsUrl: 'https://open.bigmodel.cn/dev/api',
    status: 'metadata-only',
    models: [
      { id: 'glm-4.5-air', display: 'GLM-4.5 Air', context: 128000, in: 0.1, out: 0.3, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['cheap'] },
      { id: 'glm-4.5-pro', display: 'GLM-4.5 Pro', context: 256000, in: 1, out: 4, capabilities: ['chat', 'tools', 'streaming'], status: 'GA', tags: ['frontier'] },
    ],
  },

  {
    id: 'mimo',
    name: 'Mimo AI',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://api.mimo.ai/v1',
    authType: 'oauth',
    capabilities: ['chat', 'tools', 'streaming'],
    docsUrl: 'https://mimo.org',
    status: 'planned',
    notes: 'Account/OAuth-style provider placeholder for quota-based access. Enable after official endpoint details are configured.',
    models: [
      { id: 'mimo-agent-pro', display: 'Mimo Agent Pro', context: 256000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'planned', tags: ['agent', 'oauth'] },
      { id: 'mimo-agent-lite', display: 'Mimo Agent Lite', context: 128000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'planned', tags: ['agent', 'oauth'] },
    ],
  },
  {
    id: 'kiro',
    name: 'Kiro',
    category: 'oauth',
    format: 'kiro-account',
    baseUrl: 'https://codewhisperer.us-east-1.amazonaws.com',
    authType: 'oauth-connected',
    capabilities: ['chat', 'tools', 'streaming'],
    docsUrl: 'https://kiro.dev',
    status: 'implemented',
    notes: 'Uses a connected Kiro IDE refresh token or Kiro account callback. Defaults mirror current 9router Kiro models, with Claude Opus 4.7 included as a manual test candidate because upstream users report it can work when added manually.',
    models: [
      { id: 'claude-opus-4.7', display: 'Claude Opus 4.7', context: 256000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'manual-test', tags: ['claude', 'opus', 'manual-candidate', 'oauth'] },
      { id: 'claude-opus-4.6 thinking', display: 'Claude Opus 4.6 Thinking', context: 256000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'manual-test', tags: ['claude', 'opus', 'thinking', 'manual-candidate', 'oauth'] },
      { id: 'claude-opus-4.6', display: 'Claude Opus 4.6', context: 256000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'manual-test', tags: ['claude', 'opus', 'manual-candidate', 'oauth'] },
      { id: 'claude-sonnet-4.5', display: 'Claude Sonnet 4.5', context: 256000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'oauth', tags: ['claude', 'sonnet', 'oauth'] },
      { id: 'claude-haiku-4.5', display: 'Claude Haiku 4.5', context: 200000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'oauth', tags: ['claude', 'haiku', 'oauth'] },
      { id: 'deepseek-3.2', display: 'DeepSeek 3.2', context: 128000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'oauth', tags: ['code', 'strip-image-audio', 'oauth'] },
      { id: 'qwen3-coder-next', display: 'Qwen3 Coder Next', context: 128000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'oauth', tags: ['code', 'qwen', 'strip-image-audio', 'oauth'] },
      { id: 'glm-5', display: 'GLM 5', context: 128000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'oauth', tags: ['glm', 'oauth'] },
      { id: 'MiniMax-M2.5', display: 'MiniMax M2.5', context: 128000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'oauth', tags: ['minimax', 'oauth'] },
    ],
  },
  {
    id: 'antigravity',
    name: 'Google Antigravity',
    category: 'cloud',
    format: 'openai-compatible',
    baseUrl: 'https://antigravity.google.com',
    authType: 'oauth',
    capabilities: ['chat', 'tools', 'streaming'],
    docsUrl: 'https://antigravity.google.com',
    status: 'planned',
    notes: 'Account-login provider placeholder for Antigravity-style coding quota access.',
    models: [
      { id: 'antigravity-agent', display: 'Antigravity Agent', context: 1000000, in: null, out: null, capabilities: ['chat', 'tools', 'streaming'], status: 'planned', tags: ['code', 'agent', 'oauth'] },
      { id: 'antigravity-gemini', display: 'Antigravity Gemini', context: 2000000, in: null, out: null, capabilities: ['chat', 'tools', 'vision', 'streaming'], status: 'planned', tags: ['gemini', 'oauth'] },
    ],
  },
  {
    id: 'iflytek-spark',
    name: 'iFlytek Spark',
    category: 'cloud',
    format: 'native',
    baseUrl: 'https://spark-api-open.xf-yun.com/v1',
    authType: 'bearer',
    capabilities: ['chat', 'streaming'],
    docsUrl: 'https://www.xfyun.cn/doc/spark/Web.html',
    status: 'metadata-only',
    models: [
      { id: 'spark-4-ultra', display: 'Spark 4 Ultra', context: 128000, in: 1, out: 4, capabilities: ['chat', 'streaming'], status: 'GA', tags: ['cn'] },
    ],
  },
];

export const PROVIDER_CATEGORIES = ['cloud', 'oauth', 'aggregator', 'serverless', 'local', 'image', 'embeddings', 'audio', 'custom'];

export const ALL_CAPABILITIES = ['chat', 'completion', 'embeddings', 'image', 'vision', 'audio', 'rerank', 'tools', 'streaming'];

export function getRegistry() {
  return registry;
}

export function getProviderById(id) {
  return registry.find((p) => p.id === id);
}

export function getProvidersByFormat(format) {
  return registry.filter((p) => p.format === format);
}

export function totalProviderCount() {
  return registry.length;
}

export function totalModelCount() {
  return registry.reduce((sum, p) => sum + (p.models?.length || 0), 0);
}
